"""empty message

Revision ID: 3624a2e889df
Revises: 90bbf0a6959e
Create Date: 2020-11-09 19:51:01.597406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3624a2e889df'
down_revision = '90bbf0a6959e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
