"""empty message

Revision ID: 90bbf0a6959e
Revises: bf3f2770f5d6
Create Date: 2020-11-09 19:47:04.349110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bbf0a6959e'
down_revision = 'bf3f2770f5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_assigned_to_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'assigned_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_assigned_to_fkey', 'item', 'user', ['assigned_to'], ['_id'])
    # ### end Alembic commands ###
