"""empty message

Revision ID: bf3f2770f5d6
Revises: 3cab46b75963
Create Date: 2020-11-07 22:49:50.990540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3f2770f5d6'
down_revision = '3cab46b75963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'family', ['_id'])
    op.add_column('item', sa.Column('complete', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'item', ['_id'])
    op.create_unique_constraint(None, 'list', ['_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_column('item', 'complete')
    op.drop_constraint(None, 'family', type_='unique')
    # ### end Alembic commands ###
